CREATE TABLE IF NOT EXISTS members {
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255),
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAILADDRESS VARCHAR(255) NOT NULL,
    GENDER VARCHAR(255),
    BIRTHDATE DATE
};

CREATE TABLE IF NOT EXISTS admins {
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    MEMBERID INTEGER NOT NULL,
    FOREIGN KEY(MEMBER_ID) REFERENCES members(ID)
};

